[project]
name = "yt-downloader"
version = "0.0.1"
requires-python = "~=3.13"
dependencies = [
    "fastapi[standard]>=0.116.1",
    "yt-dlp",
]

[dependency-groups]
dev = []

[tool.uv]
package = false

[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple"
