[project]
name = "yt-downloader"
version = "0.0.1"
requires-python = "~=3.13"
dependencies = [
    "fastapi[standard]>=0.116.1",
    "pydantic-settings>=2.10.1",
    "yt-dlp",
    "celery>=5.4.0",
    "redis>=5.0.0",
]

[dependency-groups]
dev = []

[tool.uv]
package = false

[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple"
